from typing import Protocol, runtime_checkable


@runtime_checkable
class BaseStorage(Protocol):
    async def save_file(self, file_id: str, content: bytes, filename: str) -> str: ...
    async def get_file(self, file_id: str, filename: str) -> bytes: ...
    async def delete_file(self, file_id: str, filename: str) -> None: ...
